name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out > report.out
        # 除外したいファイルがある場合
        # cat coverage.out |grep -E -v '(mock_*.go|*.pb.go)' > filtered.out
        # go tool cover -func=filtered.out > report.out

        # coverage rate limit
        declare -r limit=60
        if (( $(cat report.out | awk 'END{gsub("%", "", $3); print ($3 < '$limit')}') )); then
          echo 'Coverage is below the lower limit! Failed!'
          exit 1;
        fi
